Use avocado-ci-tools for static-checks
avocado-framework/autils pull request #16
Opened 2024-02-07 14:03 UTC by richtja

It uses avocado-ci-tools/static-checks for running avocado-static-checks instead directly dunning scripts from avocado-static-checks repo.

2024-02-07 14:08 UTC, richtja commented
You can see the test of changed workflow in [here](https://github.com/richtja/autils/actions/runs/7815952898/job/21320431208)

2024-02-08 20:11 UTC, clebergnu requested changes
Hi @richtja ,

There's a double checkout of the `avocado-static-checks` repo the way this is currently implemented.  One is done in the preceding step, and the other one in the action itself.

Also, the `avocado-ci-tools` will check out `avocado-static-checks` in a different location than the submodule, which does not seem to be like the best solution.  Have you looked into a possible `actions/checkout` behavior that would simply update the submodule in the location it's configured by the submodule itself?

2024-02-09 10:31 UTC, richtja commented
> Hi @richtja ,
> 
> There's a double checkout of the `avocado-static-checks` repo the way this is currently implemented. One is done in the preceding step, and the other one in the action itself.
> 
> Also, the `avocado-ci-tools` will check out `avocado-static-checks` in a different location than the submodule, which does not seem to be like the best solution. Have you looked into a possible `actions/checkout` behavior that would simply update the submodule in the location it's configured by the submodule itself?

Hi @clebergnu I see your point and understand that having the submodule twice in two different places is not the best solution. I decided to do it like this, because the avocado-ci-tools should be more general (work with and without submodules) and I thought that this is a much simpler solution. (the submodules are the reason why the avocado-ci-tools doesn't check out to root dir but to root/avocado-ci-tools/ dir). 

The other solution for this is to make avocado-ci-tools work with submodules. Which means detecting the submodule and run it if it exists instead of checkout it again.

I can implement the second solution, but I would like to make things simple, and I don't see a problem with having double checkout, but maybe I am missing something here.

2024-02-14 19:20 UTC, clebergnu commented
> > Hi @richtja ,
> > There's a double checkout of the `avocado-static-checks` repo the way this is currently implemented. One is done in the preceding step, and the other one in the action itself.
> > Also, the `avocado-ci-tools` will check out `avocado-static-checks` in a different location than the submodule, which does not seem to be like the best solution. Have you looked into a possible `actions/checkout` behavior that would simply update the submodule in the location it's configured by the submodule itself?
> 
> Hi @clebergnu I see your point and understand that having the submodule twice in two different places is not the best solution. I decided to do it like this, because the avocado-ci-tools should be more general (work with and without submodules) and I thought that this is a much simpler solution. (the submodules are the reason why the avocado-ci-tools doesn't check out to root dir but to root/avocado-ci-tools/ dir).
> 
> The other solution for this is to make avocado-ci-tools work with submodules. Which means detecting the submodule and run it if it exists instead of checkout it again.
> 
> I can implement the second solution, but I would like to make things simple, and I don't see a problem with having double checkout, but maybe I am missing something here.

There's a simpler solution: simply avoid checking out the submodules on the earlier checkout.  That is, remove the lines:

```
        with:
          submodules: true
```

Let me know if that makes sense to you.

2024-02-15 16:13 UTC, richtja commented
> > > Hi @richtja ,
> > > There's a double checkout of the `avocado-static-checks` repo the way this is currently implemented. One is done in the preceding step, and the other one in the action itself.
> > > Also, the `avocado-ci-tools` will check out `avocado-static-checks` in a different location than the submodule, which does not seem to be like the best solution. Have you looked into a possible `actions/checkout` behavior that would simply update the submodule in the location it's configured by the submodule itself?
> > 
> > 
> > Hi @clebergnu I see your point and understand that having the submodule twice in two different places is not the best solution. I decided to do it like this, because the avocado-ci-tools should be more general (work with and without submodules) and I thought that this is a much simpler solution. (the submodules are the reason why the avocado-ci-tools doesn't check out to root dir but to root/avocado-ci-tools/ dir).
> > The other solution for this is to make avocado-ci-tools work with submodules. Which means detecting the submodule and run it if it exists instead of checkout it again.
> > I can implement the second solution, but I would like to make things simple, and I don't see a problem with having double checkout, but maybe I am missing something here.
> 
> There's a simpler solution: simply avoid checking out the submodules on the earlier checkout. That is, remove the lines:
> 
> ```
>         with:
>           submodules: true
> ```
> 
> Let me know if that makes sense to you.

@clebergnu yes, you are right, this is the easiest solution. I sent force-push with the fix, please have a look.

2024-02-16 20:11 UTC, clebergnu approved these changes
LGTM, thanks!

2024-02-16 20:11 UTC, merged