Autils release process
avocado-framework/autils pull request #26
Opened 2024-11-15 13:18 UTC by richtja

This PR introduces the release workflow for autils. The release workflow can be triggered manually, or it will be triggered by release-bot after successful voting. The release workflow supports a manual trigger for creating minor version releases, which can be used for security updates or critical fixes.

The PR also introduces pre-release workflow which uses `test.pypi` to run the dry-run of the release to check release process.

Before the first release, we need to configure the `test.pypi` and `pypi` instances and create `0.0` tag to make this fully operational.

Test of the release workflow:
https://github.com/richtja/autils/actions/runs/11840187779/job/32993407763

Test of the pre-release workflow:
https://github.com/richtja/autils/actions/runs/11841451279

Test of the release-bot:
https://github.com/richtja/autils/actions/runs/11856687960

2024-11-25 10:33 UTC, clebergnu reviewed
Hi @richtja,

This looks pretty good, but I left are only two comments/questions.

Thanks!

2024-11-25 10:33 UTC, clebergnu commented on pyproject.toml
> +  "Framework :: Pytest",
Is this intentional?

2024-11-25 10:33 UTC, clebergnu commented on .github/workflows/release.yml
> +        - mayor
Maybe a typo? s/mayor/major/

2024-11-25 16:15 UTC, richtja commented on pyproject.toml
> +  "Framework :: Pytest",
After our discussion I will remove it

2024-11-25 16:17 UTC, richtja commented
Hi @clebergnu, thanks for your review. I have addressed your comments, please have a look.

2024-11-27 00:50 UTC, clebergnu approved these changes
LGTM, thanks!

2024-11-27 00:55 UTC, clebergnu requested changes
Actually, I caught an issue.

The "name" of the project (under `pyproject.toml`, `[project]`) needs to be lowercase "autils" too.  Or else, the build process would generate:

```
Successfully built autils-0.1.dev47+gfa9c2de.tar.gz and Autils-0.1.dev47+gfa9c2de-py3-none-any.whl
```

Which I don't think it's intended.

2024-11-27 09:22 UTC, richtja commented
> Actually, I caught an issue.
> 
> The "name" of the project (under `pyproject.toml`, `[project]`) needs to be lowercase "autils" too. Or else, the build process would generate:
> 
> ```
> Successfully built autils-0.1.dev47+gfa9c2de.tar.gz and Autils-0.1.dev47+gfa9c2de-py3-none-any.whl
> ```
> 
> Which I don't think it's intended.

Right, good catch. I will fix it.

2024-11-27 14:47 UTC, clebergnu approved these changes
LGTM, thanks!

2024-11-27 14:48 UTC, merged